### PR TITLE
Removed 'px'  and added on hover, active effect

### PR DESCRIPTION
**Pull request by voltrare**
removed 'px' only based on last commit
added hover effect on chapter, episode card

### CODE REVIEW

**Comment by AriaMoradi** [comment]
> removed 'px' only based on last commit

why?

**Comment by voltrare** [comment]
ah wait i am uploading the screenshot
dhul0ly7BV

> why?
ah because most of the css doesnt have 'px' so i thought this is to make it consistent
> Image?
only for the chaptercard and episode card

**Comment by AriaMoradi** [comment]
The hover effect is really cool, a fine addition

> most of the css doesnt have 'px'

That's wrong, if it's missing the px, then the dev was lazy

**Comment by AriaMoradi** [comment]
About the image it's for the style prop, not jss

**Comment by voltrare** [comment]
ah ill change it back

**Comment by AriaMoradi** [comment]
If you want make px units consistent then do it in a separate PR
Each PR should change one topic

**Comment by voltrare** [comment]
allright then thanks for the insight

**Comment by voltrare** [comment]
i should close this

**Pull request closed without merging**
