### PR TITLE
Feature/force absolute import path

### PR DESCRIPTION
**Pull request by schroda**

### CODE REVIEW

**Review by AriaMoradi — CHANGES_REQUESTED** [review]
I don't like this one in particular, replace `src` with `@`

**Comment by schroda** [comment]
> I don't like this one in particular, replace `src` with `@`

what about `@webUI`?

**Comment by AriaMoradi** [comment]
> > I don't like this one in particular, replace `src` with `@`
> 
> what about `@webUI`?

why? we don't have some other root than `src`?

**Comment by schroda** [comment]
> > > I don't like this one in particular, replace `src` with `@`
> > 
> > 
> > what about `@webUI`?
> 
> why? we don't have some other root than `src`?

I guess I'm missing something, what exactly do you mean with replace `src` with `@`?
(1.) `src/component/...` -> `@/component/...`
or
(2.) `src/component/...` -> `@component/...`

(1.) doesn't work, would have to be `@<XYZ>/components...`


but ignoring all that, it looks like create-react-app doesn't support alias imports anymore (tsconfig -> "paths"...).

> yarn start
yarn run v1.22.19
$ react-scripts start
The following changes are being made to your tsconfig.json file:
>  - compilerOptions.paths must not be set (aliased imports are not supported)

I don't really know how else I could do it?

**Comment by AriaMoradi** [comment]
take a look: https://github.com/ixartz/Next-js-Boilerplate/blob/81e3f7160b8ec977526427d25ea8f7dcb60ee2c2/tsconfig.json#L40

**Comment by AriaMoradi** [comment]
> looks like create-react-app doesn't support alias imports anymore
> 
> > Now that is a problem

Compare
```jsx
import MyComponent from '@/components/MyComponent';
```
vs
```jsx
import MyComponent from 'src/components/MyComponent';
```
- The first one has a clear visual indicator that we are importing local code, the second not so much.
- That's the syntax I like to see anyway, if CRA doesn't want to support it then either give up or find an alternative solution?

Looks like I have to reject this? why would we even bother making absolute imports and starting from `src` mandatory? It's just more typing...

**Comment by schroda** [comment]
> That's the syntax I like to see anyway, if CRA doesn't want to support it then either give up or find an alternative solution?
ye then I guess we leave it as it is

> The first one has a clear visual indicator that we are importing local code, the second not so much.
I get what you mean but since it's not as straight forwards to do it as I thought I'm not going to invest more time in reasearching

I'd say doing it with `src` is closer to your liked solution (`@`)  then how it's currently done (`component/...` or `screen/...`) since there is no visual identification that it's from the same source

> why would we even bother making absolute imports and starting from src mandatory? It's just more typing...

absolute imports: `CONTRIBUTING.md` -> `Coding Style Guide`:
> Don't use relative imports.


> It's just more typing...

I mean the IDE is doing everything for you


but in the end it's your call if you prefer the way it's done currently you can just reject it of course

**Comment by AriaMoradi** [comment]
considering everything and that we set a rule to not have absolute imports, if something like `@src/` works then it shall be so, but if we can't include `@` then let's just have the no relative import lint rule and keep the `src/` part out as it's redundant path your eye doesn't need to see, on the other hand, at least one can make some sense in their mind `components/..` means we are using a component, that some beneficial visual indication if I say so myself.

**Comment by schroda** [comment]
Alright, then it's the no relative import rule without `src` since alias imports do not work at all with CRA, gets removed from the tsconfig once you run a script (e.g. `start` or `build`)


----

`@/...` would work without CRA, it was just an issue with the eslint settings from `airbnb` (`ESLint: Missing file extension for "@/util/client"(import/extensions)`)

regarding `@/...`, `src/...` or `components/...` I guess we agree to disagree 😆 
me personally idc if it would be `@` or `src`, I don't really see a difference there, but regarding `components/...` I'd say it's not really clear were it's coming from, ofc you can tell that it's components that you are using, but you can't really tell if it's local or from some library.
I mean e.g. you could have a local folder named exactly like a library that you're using and then it would be possible to have an import for the library and for files from the local folder, which would just be confusing.

**Comment by AriaMoradi** [comment]
> I mean e.g. you could have a local folder named exactly like a library that you're using and then it would be possible to have an import for the library and for files from the local folder, which would just be confusing.

In that case I would agree with your point, but we don't have such issue with this code base.

**Review by AriaMoradi — APPROVED** [review]

**Pull request merged**
