### PR TITLE
Add GitHub Action to run tsc on push

### PR DESCRIPTION
**Pull request by schroda**

### CODE REVIEW

**Comment by AriaMoradi** [comment]
Also add this to pull request checks.

**Comment by schroda** [comment]
you can make the action "code-checks" required to pass for merging to be allowed (branch protection rule -> require status cehcks to pass before merging)

**Comment by AriaMoradi** [comment]
> Also add this to pull request checks.

What I am reffering to is
https://github.com/Suwayomi/Tachidesk-Server/blob/master/.github/workflows/build_pull_request.yml

Look at the directory as well.

**Comment by schroda** [comment]
> It should run everything we do for push up until making a release.

currently it runs on every push, so I think adding "pull_request" doesn't really add anything, unless it should only run for pull requests and ignore other branches (so replacing "push" with "pull_request")?


> Look at the directory as well.

not sure what you mean


> you can make the action "code-checks" required to pass for merging to be allowed (branch protection rule -> require status checks to pass before merging)

I think adding this after the pr is merged would still make sense just to make it a little safer

**Comment by schroda** [comment]
I think this should be fine now

**Comment by AriaMoradi** [comment]
@akabhirav review please

**Review by akabhirav — APPROVED** [review]
LGTM

**Pull request merged**
