### PR TITLE
Source filters, move search to SourceMangas

### PR DESCRIPTION
**Pull request by Robonau**
implementation of the `/api/v1/source/{sourceId}/filters` endpoint

Screenshot_20220301_222850
right side (mangadex, different per source):

Screenshot_20220301_222926

groups appear on top of the filters:
Screenshot_20220301_223010

something JUI already implemented

### CODE REVIEW

**Comment by Robonau** [comment]
should i combine search in to browse
or should i move filtering over to search?
(personally i thing combining search in to browse makes more sense)
i currently have filter coded for the browse page (/popular), but filtering on the /search endpoint

**Comment by Robonau** [comment]
rather than using resetFilterValue and updateFilterValue i should probably use a useState
and pass through the set

2. spamming too many options in quick succession will break it

**Comment by AriaMoradi** [comment]
your commit naming is fun

**Comment by Robonau** [comment]
i never know what to actually call my commits, so they tend to get pretty random

worked out the breaking that was happening in the last commit.
im probably using useState for more than is necessary, only really needed to do triggerUpdate and Data.
but im done for now, imma open for review.

**Comment by Robonau** [comment]
screenshots update:
Screenshot_20220303_232253
Screenshot_20220303_232841
Screenshot_20220303_232853
Screenshot_20220303_232917

**Pull request merged**
