### PR TITLE
make default reader settings changeable

### LINKED ISSUE #214: [Feature Request] The default reader settings should be changable
## What feature should be added to Tachidesk?
The default reader settings used for mangas that haven't been read yet should be changeable in the settings.

##  Why/Project's Benefit/Existing Problem
In case you use the same reader settings most of the time and are only changing them for some mangas, it is annoying to always have to change the "default" used reader settings

### PR DESCRIPTION
**Pull request by schroda**
Closes #214

### CODE REVIEW

**Comment by schroda** [comment]
- wait for #213 to be merged
- rebase onto master

**Comment by schroda** [comment]
rebased onto #213

**Comment by AriaMoradi** [comment]
rebase

**Comment by schroda** [comment]
> rebase please

done

**Pull request merged**
