### PR TITLE
Invert Double Page switch

### PR DESCRIPTION
**Pull request by rickymcmuffin**
I added a toggle that switches which page comes first in double page mode.

Before: 
beforeWebUI

After:
Screenshot 2023-09-07 112618

Here's with it off:
image

Here's with it on:
image

It is currently a work in progress. Features I want to add are:

- The toggle hides when not in double page mode.
- The pages switch instantly when clicking the toggle.

This closes the issue I made #416

### CODE REVIEW

**Comment by rickymcmuffin** [comment]
Finished the changes. Let me know what you think!

**Comment by schroda** [comment]
looks good, just a few things

since the setting only effects the double page reader, it should only be shown in case it is selected

I think "offset first page" would describes the behaviour better
the first time I read "invert double page" I didn't understand it and what it is supposed to do

not really relevant, but I would leave the "reader type" as the last setting, I think it looks better this way

**Comment by rickymcmuffin** [comment]
I made all the changes.

**Comment by schroda** [comment]
nice job improving the double page reader 👍

looks like there is also some issue with viewing a not downloaded/cached chapter with the double page reader, if you're interesed in taking a look at it

**Pull request merged**
